# Specialized CICD script to run on gitlab.com: only run unittests on tags
stages:
  - pre_release
  - release

flake8:
  tags:
    - linux
    - docker
  image: python:3
  stage: pre_release
  script:
    - pip install black flake8 flake8-black pep8-naming flake8-bugbear --constraint requirements-dev.txt
    - flake8 -v mixer tests extra

zip:
  tags:
    - linux
  stage: pre_release
  script:
    - cp CHANGELOG.md README.md LICENSE mixer/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - mixer
    expire_in: 1 week

.on_version_tag: &tpl_on_version_tag
  only:
    refs:
      # see inject_version.py
      - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(\-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$/

release:
  <<: *tpl_on_version_tag
  dependencies:
    - zip
  tags:
    - linux
    - docker
  image: python:3
  stage: release
  script:
    - pip install requests
    - python -m zipfile -c mixer-${CI_COMMIT_REF_NAME}.zip mixer/
    - python -m gitlab.release mixer-${CI_COMMIT_REF_NAME}.zip
  artifacts:
    paths:
      - mixer-${CI_COMMIT_REF_NAME}.zip

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md
unittest:
  <<: *tpl_on_version_tag
  stage: pre_release
  tags:
    - blender
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip-tests\]/
  variables:
    MIXER_BLENDER_ZIP_BASENAME: blender-2.82a-windows64
    MIXER_BLENDER_VERSION_BASE: "2.82"
    MIXER_BASH_EXE: C:\Program Files\Git\bin\bash.exe
    VRTIST_PORT: 25600 # In case a server is already running on our default port on the test computer
    MIXER_TEST_OUTPUT: logs\tests
  script:
    - gitlab\run_unittest.bat
  cache:
    paths:
      - gitlab/blender/cache
  artifacts:
    paths:
      - logs\tests\*.xml
    reports:
      junit:
        - logs\tests\*.xml